import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const initialBlogs = [
  {
    title: 'Understanding DEWA Shams Dubai Solar Policy',
    slug: 'understanding-dewa-shams-dubai-solar-policy',
    subtitle: 'A complete regulatory roadmap for utility metering',
    content: `<h3>The Shams Dubai Net Metering Initiative</h3>
<p>Shams Dubai is the official utility parallel grid connection regulation established by the Dubai Electricity and Water Authority (DEWA). Under this framework, commercial warehouses, industrial manufacturing plants, and residential villa homeowners can install photovoltaic (PV) solar systems on their rooftops and connect them parallelly to the utility grid network.</p>

<blockquote>"Shams Dubai allows excess electricity generated by solar arrays to be exported back to the DEWA grid, automatically rolling over energy credits to reduce future grid bills."</blockquote>

<h3>How Net Metering Works</h3>
<p>When your solar panels generate more electricity than your building consumes (usually during peak sunlight between 10:00 AM and 3:00 PM), the net excess energy flows backward through a smart bidirectional meter installed by DEWA. Your account receives credits for every Kilowatt-hour (kWh) exported. These credits do not expire and are deducted from your grid consumption billing at the end of the month.</p>

<h3>Key Regulatory Steps</h3>
<ol>
  <li><strong>No Objection Certificate (NOC):</strong> Submission of structural drawings and electricity load limits.</li>
  <li><strong>Design Approval:</strong> Engineering review of solar layouts, inverters, and utility switchgears.</li>
  <li><strong>Installation:</strong> PV installation by DEWA-certified solar contractors.</li>
  <li><strong>Testing & Commissioning:</strong> Inspections, grid synchronization, and meter installation.</li>
</ol>

<h3>Frequently Asked Questions</h3>
<h4>Can I sell excess energy for cash?</h4>
<p>No, the Shams Dubai regulation operates on a net billing credit mechanism. Excess energy is accumulated as credits to offset future electricity bills on the same account; it is not sold back for cash payouts.</p>
<h4>Who manages the approvals process?</h4>
<p>GOL LOW manages the entire Shams Dubai connection pipeline, including engineering schematics, solar meter requests, and final DEWA inspections, with zero hassle to the customer.</p>`,
    category: 'Regulations',
    author: 'Tariq Mahmoud',
    tags: 'dewa,shams,net metering,dubai',
    readTime: '6 min read',
    imageUrl: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&q=80&w=800'
  },
  {
    title: 'Diesel vs. Solar Hybrid Sizing for UAE Construction Sites',
    slug: 'diesel-vs-solar-hybrid-sizing-for-uae-construction-sites',
    subtitle: 'Decarbonizing remote sites with trailer container arrays',
    content: `<h3>Replacing Remote Diesel Power Plants</h3>
<p>Remote construction highway worksites, oil/gas camps, and infrastructure sites across the UAE have traditionally relied on heavy diesel generator plants running 24/7. These generators suffer from high fuel prices, noisy engine cycles, localized pollution, and constant maintenance intervals.</p>

<p>GOL LOW's modular solar container units provide a reliable alternative. By pairing mobile containerized PV arrays with industrial-grade lithium battery storage cabinets, we create clean solar-diesel-battery hybrid grids.</p>

<blockquote>"By running solar containers during daylight hours and storing excess energy in batteries for twilight shifts, projects cut diesel consumption by up to 60%."</blockquote>

<h3>Sizing a Hybrid Construction Setup</h3>
<p>To accurately size a hybrid solar system for a construction site, our design engineers evaluate:</p>
<ul>
  <li><strong>Peak load capacity (kW):</strong> Standard sizing ranges from 50kW to 1MW peak startup currents.</li>
  <li><strong>Continuous base load (kW):</strong> Off-shift power requirements for site offices and security systems.</li>
  <li><strong>Daily fuel burn (Litres):</strong> Traditional generators consume roughly 0.27 litres of diesel per generated kWh.</li>
</ul>

<h3>Financial and Environmental ROI</h3>
<p>Leasing solar containers provides immediate savings:
- Zero upfront CAPEX (rental fee starts after setup is active).
- Immediate reduction in diesel deliveries, fuel storage risks, and spill hazards.
- Maintenance is fully managed by GOL LOW technicians, avoiding construction project downtime.</p>`,
    category: 'Engineering',
    author: 'Sarah Jenkins',
    tags: 'construction,hybrid,diesel offset,battery storage',
    readTime: '8 min read',
    imageUrl: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&q=80&w=800'
  },
  {
    title: 'How Often Should Rooftop Solar Panels Be Cleaned in Dubai?',
    slug: 'how-often-should-rooftop-solar-panels-be-cleaned-in-dubai',
    subtitle: 'Combating dust and humidity losses in desert environments',
    content: `<h3>The Challenge of Soiling in the UAE</h3>
<p>The desert climate of the United Arab Emirates presents unique challenges for photovoltaic solar arrays. Dust storms, sand drift, and high relative humidity combine to form a baked-on layer of grime (referred to as soiling) on panel glass surfaces.</p>

<blockquote>"Uncleaned solar panels in the UAE can suffer from soiling efficiency drops of 15% to 30% within a single month if left unmaintained."</blockquote>

<h3>The Cleaning Cycle</h3>
<p>To ensure GOL LOW rented solar arrays produce peak output, we implement strict automated and manual cleaning intervals:</p>
<ol>
  <li><strong>Weekly dry-sweeping:</strong> Using specialized non-abrasive solar brushes to clear loose sand dust.</li>
  <li><strong>Bi-weekly waterless cleaning:</strong> Utilizing electrostatic dust-repelling brushes that clear dust without consuming water.</li>
  <li><strong>Monthly deep washing:</strong> Scheduled early-morning water sweeps to dissolve caked mud and salt crusts.</li>
</ol>

<h3>Why Manual Washing in Afternoon is Avoided</h3>
<p>Washing hot solar panels (surface temperatures can exceed 70°C in summer) with cold water induces severe thermal shock, leading to micro-cracks in silicon solar cells and shattering the tempered glass front. Cleaning is strictly performed between 5:00 AM and 8:00 AM or after sunset.</p>`,
    category: 'Maintenance',
    author: 'O&M Support Team',
    tags: 'cleaning,soiling,dust,operations',
    readTime: '4 min read',
    imageUrl: 'https://images.unsplash.com/photo-1613665813446-82a78c468a1d?auto=format&fit=crop&q=80&w=800'
  }
];

const formulaConfigs = [
  { key: 'rate_residential', value: 36, description: 'Monthly lease fee in AED per kWp for residential solar installations.' },
  { key: 'rate_commercial', value: 28, description: 'Monthly lease fee in AED per kWp for commercial installations.' },
  { key: 'rate_industrial', value: 20, description: 'Monthly lease fee in AED per kWp for industrial factory installations.' },
  { key: 'rate_construction', value: 48, description: 'Monthly lease fee in AED per kWp for short-term temporary construction sites.' },
  { key: 'rate_battery', value: 32, description: 'Monthly lease fee in AED per kWh for battery energy storage systems.' },
  { key: 'solar_yield_multiplier', value: 145, description: 'Estimated monthly energy generation in kWh per installed kWp in the UAE.' },
  { key: 'co2_multiplier', value: 0.55, description: 'Tons of carbon emissions offset per Megawatt-hour (MWh) generated.' }
];

async function main() {
  console.log('Seeding GOL LOW Solar database...');

  // 1. Seed Admin User
  const adminEmail = 'Hr@gollowsolarenergy.com';
  const existingAdmin = await prisma.user.findUnique({ where: { email: adminEmail } });
  
  if (!existingAdmin) {
    const passwordHash = await bcrypt.hash('GollowAdmin2026!', 10);
    await prisma.user.create({
      data: {
        email: adminEmail,
        passwordHash,
        role: 'admin'
      }
    });
    console.log(`- Created Admin Account: ${adminEmail} (PW: GollowAdmin2026!)`);
  } else {
    console.log(`- Admin Account already exists`);
  }

  // 2. Seed Initial Blogs
  for (const blog of initialBlogs) {
    await prisma.blog.upsert({
      where: { slug: blog.slug },
      update: {},
      create: blog
    });
  }
  console.log(`- Seeded ${initialBlogs.length} Blog posts`);

  // 3. Seed Sizing Formulas
  for (const config of formulaConfigs) {
    await prisma.formulaConfig.upsert({
      where: { key: config.key },
      update: {},
      create: config
    });
  }
  console.log(`- Seeded ${formulaConfigs.length} Pricing and yield formulas`);

  console.log('Seeding complete!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
