// src/mockApi.js
// Client-side Mock API intercepting window.fetch
// Stores data in localStorage to behave like a persistent database.

const initialBlogs = [
  {
    id: 'b1',
    title: 'Understanding DEWA Shams Dubai Solar Policy',
    slug: 'understanding-dewa-shams-dubai-solar-policy',
    subtitle: 'A complete regulatory roadmap for utility metering',
    content: `<h3>The Shams Dubai Net Metering Initiative</h3>
<p>Shams Dubai is the official utility parallel grid connection regulation established by the Dubai Electricity and Water Authority (DEWA). Under this framework, commercial warehouses, industrial manufacturing plants, and residential villa homeowners can install photovoltaic (PV) solar systems on their rooftops and connect them parallelly to the utility grid network.</p>

<blockquote>"Shams Dubai allows excess electricity generated by solar arrays to be exported back to the DEWA grid, automatically rolling over energy credits to reduce future grid bills."</blockquote>

<h3>How Net Metering Works</h3>
<p>When your solar panels generate more electricity than your building consumes (usually during peak sunlight between 10:00 AM and 3:00 PM), the net excess energy flows backward through a smart bidirectional meter installed by DEWA. Your account receives credits for every Kilowatt-hour (kWh) exported. These credits do not expire and are deducted from your grid consumption billing at the end of the month.</p>

<h3>Key Regulatory Steps</h3>
<ol>
  <li><strong>No Objection Certificate (NOC):</strong> Submission of structural drawings and electricity load limits.</li>
  <li><strong>Design Approval:</strong> Engineering review of solar layouts, inverters, and utility switchgears.</li>
  <li><strong>Installation:</strong> PV installation by DEWA-certified solar contractors.</li>
  <li><strong>Testing & Commissioning:</strong> Inspections, grid synchronization, and meter installation.</li>
</ol>

<h3>Frequently Asked Questions</h3>
<h4>Can I sell excess energy for cash?</h4>
<p>No, the Shams Dubai regulation operates on a net billing credit mechanism. Excess energy is accumulated as credits to offset future electricity bills on the same account; it is not sold back for cash payouts.</p>
<h4>Who manages the approvals process?</h4>
<p>GOL LOW manages the entire Shams Dubai connection pipeline, including engineering schematics, solar meter requests, and final DEWA inspections, with zero hassle to the customer.</p>`,
    category: 'Regulations',
    author: 'Tariq Mahmoud',
    tags: 'dewa,shams,net metering,dubai',
    readTime: '6 min read',
    imageUrl: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&q=80&w=800',
    publishedAt: '2026-07-08T04:20:00.000Z'
  },
  {
    id: 'b2',
    title: 'Diesel vs. Solar Hybrid Sizing for UAE Construction Sites',
    slug: 'diesel-vs-solar-hybrid-sizing-for-uae-construction-sites',
    subtitle: 'Decarbonizing remote sites with trailer container arrays',
    content: `<h3>Replacing Remote Diesel Power Plants</h3>
<p>Remote construction highway worksites, oil/gas camps, and infrastructure sites across the UAE have traditionally relied on heavy diesel generator plants running 24/7. These generators suffer from high fuel prices, noisy engine cycles, localized pollution, and constant maintenance intervals.</p>

<p>GOL LOW\'s modular solar container units provide a reliable alternative. By pairing mobile containerized PV arrays with industrial-grade lithium battery storage cabinets, we create clean solar-diesel-battery hybrid grids.</p>

<blockquote>"By running solar containers during daylight hours and storing excess energy in batteries for twilight shifts, projects cut diesel consumption by up to 60%."</blockquote>

<h3>Sizing a Hybrid Construction Setup</h3>
<p>To accurately size a hybrid solar system for a construction site, our design engineers evaluate:</p>
<ul>
  <li><strong>Peak load capacity (kW):</strong> Standard sizing ranges from 50kW to 1MW peak startup currents.</li>
  <li><strong>Continuous base load (kW):</strong> Off-shift power requirements for site offices and security systems.</li>
  <li><strong>Daily fuel burn (Litres):</strong> Traditional generators consume roughly 0.27 litres of diesel per generated kWh.</li>
</ul>

<h3>Financial and Environmental ROI</h3>
<p>Leasing solar containers provides immediate savings:
- Zero upfront CAPEX (rental fee starts after setup is active).
- Immediate reduction in diesel deliveries, fuel storage risks, and spill hazards.
- Maintenance is fully managed by GOL LOW technicians, avoiding construction project downtime.</p>`,
    category: 'Engineering',
    author: 'Sarah Jenkins',
    tags: 'construction,hybrid,diesel offset,battery storage',
    readTime: '8 min read',
    imageUrl: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&q=80&w=800',
    publishedAt: '2026-07-08T04:21:00.000Z'
  },
  {
    id: 'b3',
    title: 'How Often Should Rooftop Solar Panels Be Cleaned in Dubai?',
    slug: 'how-often-should-rooftop-solar-panels-be-cleaned-in-dubai',
    subtitle: 'Combating dust and humidity losses in desert environments',
    content: `<h3>The Challenge of Soiling in the UAE</h3>
<p>The desert climate of the United Arab Emirates presents unique challenges for photovoltaic solar arrays. Dust storms, sand drift, and high relative humidity combine to form a baked-on layer of grime (referred to as soiling) on panel glass surfaces.</p>

<blockquote>"Uncleaned solar panels in the UAE can suffer from soiling efficiency drops of 15% to 30% within a single month if left unmaintained."</blockquote>

<h3>The Cleaning Cycle</h3>
<p>To ensure GOL LOW rented solar arrays produce peak output, we implement strict automated and manual cleaning intervals:</p>
<ol>
  <li><strong>Weekly dry-sweeping:</strong> Using specialized non-abrasive solar brushes to clear loose sand dust.</li>
  <li><strong>Bi-weekly waterless cleaning:</strong> Utilizing electrostatic dust-repelling brushes that clear dust without consuming water.</li>
  <li><strong>Monthly deep washing:</strong> Scheduled early-morning water sweeps to dissolve caked mud and salt crusts.</li>
</ol>

<h3>Why Manual Washing in Afternoon is Avoided</h3>
<p>Washing hot solar panels (surface temperatures can exceed 70°C in summer) with cold water induces severe thermal shock, leading to micro-cracks in silicon solar cells and shattering the tempered glass front. Cleaning is strictly performed between 5:00 AM and 8:00 AM or after sunset.</p>`,
    category: 'Maintenance',
    author: 'O&M Support Team',
    tags: 'cleaning,soiling,dust,operations',
    readTime: '4 min read',
    imageUrl: 'https://images.unsplash.com/photo-1613665813446-82a78c468a1d?auto=format&fit=crop&q=80&w=800',
    publishedAt: '2026-07-08T04:22:00.000Z'
  }
];

const formulaConfigs = [
  { id: 'f1', key: 'rate_residential', value: 36, description: 'Monthly lease fee in AED per kWp for residential solar installations.' },
  { id: 'f2', key: 'rate_commercial', value: 28, description: 'Monthly lease fee in AED per kWp for commercial installations.' },
  { id: 'f3', key: 'rate_industrial', value: 20, description: 'Monthly lease fee in AED per kWp for industrial factory installations.' },
  { id: 'f4', key: 'rate_construction', value: 48, description: 'Monthly lease fee in AED per kWp for short-term temporary construction sites.' },
  { id: 'f5', key: 'rate_battery', value: 32, description: 'Monthly lease fee in AED per kWh for battery energy storage systems.' },
  { id: 'f6', key: 'solar_yield_multiplier', value: 145, description: 'Estimated monthly energy generation in kWh per installed kWp in the UAE.' },
  { id: 'f7', key: 'co2_multiplier', value: 0.55, description: 'Tons of carbon emissions offset per Megawatt-hour (MWh) generated.' }
];

const mockInquiries = [
  {
    id: 'inq-1',
    name: 'Dharmik Jinjala',
    company: 'GOL LOW Rental Systems',
    email: 'dharmikjinjala2711@gmail.com',
    phone: '+971 4 337 7881',
    emirate: 'Dubai',
    propertyType: 'Commercial',
    projectType: 'General Inquiry',
    roofSize: 120,
    bill: 3000,
    contactMethod: 'Email',
    preferredDate: null,
    preferredTime: null,
    message: 'Looking for warehouse sizing options.',
    status: 'Pending',
    type: 'General',
    createdAt: '2026-07-08T04:28:50.026Z'
  }
];

const originalFetch = window.fetch;

window.fetch = async function (url, options = {}) {
  const urlStr = typeof url === 'string' ? url : url.url || '';

  // Intercept only /api endpoints
  if (!urlStr.includes('/api/')) {
    return originalFetch.apply(this, arguments);
  }

  const method = (options.method || 'GET').toUpperCase();
  let body = null;
  if (options.body) {
    try {
      body = JSON.parse(options.body);
    } catch (e) {
      body = options.body;
    }
  }

  // Parse path and query
  const pathname = urlStr.split('?')[0].replace(/^(https?:\/\/[^\/]+)?/, '');
  const searchParams = new URLSearchParams(urlStr.split('?')[1] || '');

  // Helper response builders
  const jsonResponse = (data, status = 200) => {
    return new Response(JSON.stringify(data), {
      status,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, Authorization',
      }
    });
  };

  // Mock latencies
  await new Promise(resolve => setTimeout(resolve, 150));

  // Initialize store helper
  const getStore = (key, defaultData) => {
    if (!localStorage.getItem(key)) {
      localStorage.setItem(key, JSON.stringify(defaultData));
    }
    return JSON.parse(localStorage.getItem(key));
  };
  
  const setStore = (key, data) => {
    localStorage.setItem(key, JSON.stringify(data));
  };

  const checkAuth = () => {
    const authHeader = options.headers?.Authorization || options.headers?.authorization;
    if (!authHeader || !authHeader.startsWith('Bearer mock-jwt-token-2026')) {
      return false;
    }
    return true;
  };

  // 1. Auth Endpoint
  if (pathname === '/api/auth/login' && method === 'POST') {
    const { email, password } = body || {};
    if (email === 'Hr@gollowsolarenergy.com' && password === 'GollowAdmin2026!') {
      return jsonResponse({
        token: 'mock-jwt-token-2026',
        user: { id: 'admin-1', email, role: 'admin' }
      });
    }
    return jsonResponse({ error: 'Invalid email or password.' }, 401);
  }

  // 2. Stats Dashboard
  if (pathname === '/api/dashboard/stats' && method === 'GET') {
    if (!checkAuth()) return jsonResponse({ error: 'Access denied. No token provided.' }, 401);
    const inquiries = getStore('gollow_inquiries', mockInquiries);
    const subscribers = getStore('gollow_subscribers', []);
    const blogs = getStore('gollow_blogs', initialBlogs);
    const totalSizedKw = inquiries.reduce((sum, item) => sum + ((item.roofSize || 0) / 6), 0);
    return jsonResponse({
      inquiriesCount: inquiries.length,
      subscribersCount: subscribers.filter(s => s.active).length,
      blogsCount: blogs.length,
      totalSizedKw: parseFloat(totalSizedKw.toFixed(1))
    });
  }

  // 3. Inquiries
  if (pathname === '/api/inquiries') {
    if (method === 'GET') {
      if (!checkAuth()) return jsonResponse({ error: 'Access denied. No token provided.' }, 401);
      let inquiries = getStore('gollow_inquiries', mockInquiries);
      
      const status = searchParams.get('status');
      const type = searchParams.get('type');
      const search = searchParams.get('search');
      
      if (status) inquiries = inquiries.filter(i => i.status === status);
      if (type) inquiries = inquiries.filter(i => i.type === type);
      if (search) {
        const query = search.toLowerCase();
        inquiries = inquiries.filter(i => 
          i.name.toLowerCase().includes(query) || 
          (i.company && i.company.toLowerCase().includes(query)) ||
          i.email.toLowerCase().includes(query)
        );
      }
      // Sort desc
      inquiries.sort((a,b) => new Date(b.createdAt) - new Date(a.createdAt));
      return jsonResponse(inquiries);
    }
    
    if (method === 'POST') {
      const inqs = getStore('gollow_inquiries', mockInquiries);
      const newInq = {
        id: 'inq-' + Math.random().toString(36).substr(2, 9),
        name: body.name,
        company: body.company || '',
        email: body.email,
        phone: body.phone,
        emirate: body.emirate || 'Dubai',
        propertyType: body.propertyType || 'Commercial',
        projectType: body.projectType || 'Rooftop Solar',
        roofSize: body.roofSize ? Number(body.roofSize) : 0,
        bill: body.bill ? Number(body.bill) : 0,
        contactMethod: body.contactMethod || 'Email',
        preferredDate: body.preferredDate || null,
        preferredTime: body.preferredTime || null,
        message: body.message || '',
        status: 'Pending',
        type: body.type || 'General',
        createdAt: new Date().toISOString()
      };
      inqs.push(newInq);
      setStore('gollow_inquiries', inqs);
      
      // Simulate backend log notifications in browser console
      console.log('====== [MOCK EMAIL ALERTS] ======');
      console.log(`Receipt sent to customer: ${newInq.email}`);
      console.log(`Notification sent to admin: Hr@gollowsolarenergy.com\nDetails:`, newInq);
      
      return jsonResponse({
        success: true,
        message: 'Inquiry submitted successfully.',
        data: newInq
      }, 201);
    }
  }

  // 4. Update Inquiry Status
  if (pathname.match(/^\/api\/inquiries\/[^\/]+\/status$/) && method === 'PUT') {
    if (!checkAuth()) return jsonResponse({ error: 'Access denied. No token provided.' }, 401);
    const id = pathname.split('/')[3];
    const inqs = getStore('gollow_inquiries', mockInquiries);
    const idx = inqs.findIndex(i => i.id === id);
    if (idx !== -1) {
      inqs[idx].status = body.status;
      setStore('gollow_inquiries', inqs);
      return jsonResponse(inqs[idx]);
    }
    return jsonResponse({ error: 'Inquiry not found.' }, 404);
  }

  // 5. Delete Inquiry
  if (pathname.match(/^\/api\/inquiries\/[^\/]+$/) && method === 'DELETE') {
    if (!checkAuth()) return jsonResponse({ error: 'Access denied. No token provided.' }, 401);
    const id = pathname.split('/')[3];
    let inqs = getStore('gollow_inquiries', mockInquiries);
    inqs = inqs.filter(i => i.id !== id);
    setStore('gollow_inquiries', inqs);
    return jsonResponse({ success: true, message: 'Inquiry record deleted.' });
  }

  // 6. Export Inquiries
  if (pathname === '/api/inquiries/export' && method === 'GET') {
    if (!checkAuth()) return jsonResponse({ error: 'Access denied. No token provided.' }, 401);
    const inquiries = getStore('gollow_inquiries', mockInquiries);
    let csvContent = 'ID,Name,Company,Email,Phone,Emirate,Property Type,Roof Size (m2),Bill (AED),Preferred Contact,Date,Time,Status,Type,Created At\n';
    inquiries.forEach((item) => {
      const row = [
        item.id,
        `"${item.name.replace(/"/g, '""')}"`,
        `"${(item.company || '').replace(/"/g, '""')}"`,
        item.email,
        `"${item.phone}"`,
        item.emirate,
        item.propertyType,
        item.roofSize,
        item.bill,
        item.contactMethod,
        item.preferredDate || '',
        item.preferredTime || '',
        item.status,
        item.type,
        item.createdAt,
      ].join(',');
      csvContent += row + '\n';
    });
    return new Response(csvContent, {
      status: 200,
      headers: {
        'Content-Type': 'text/csv',
        'Content-Disposition': 'attachment; filename=gollow_solar_inquiries.csv'
      }
    });
  }

  // 7. Newsletter Subscriptions
  if (pathname === '/api/newsletter/subscribe' && method === 'POST') {
    const email = body.email;
    if (!email) return jsonResponse({ error: 'Email address is required.' }, 400);
    const subs = getStore('gollow_subscribers', []);
    const existing = subs.find(s => s.email === email);
    if (existing) {
      if (existing.active) {
        return jsonResponse({ error: 'This email is already subscribed.' }, 409);
      } else {
        existing.active = true;
        setStore('gollow_subscribers', subs);
        return jsonResponse({ success: true, message: 'Subscription reactivated!' });
      }
    }
    const newSub = { id: 'sub-' + Date.now(), email, active: true, subscribedAt: new Date().toISOString() };
    subs.push(newSub);
    setStore('gollow_subscribers', subs);
    console.log(`Newsletter welcome email sent to: ${email}`);
    return jsonResponse({ success: true, subscriber: newSub }, 201);
  }

  if (pathname === '/api/newsletter/subscribers' && method === 'GET') {
    if (!checkAuth()) return jsonResponse({ error: 'Access denied. No token provided.' }, 401);
    const subs = getStore('gollow_subscribers', []);
    return jsonResponse(subs);
  }

  if (pathname === '/api/newsletter/subscribers/export' && method === 'GET') {
    if (!checkAuth()) return jsonResponse({ error: 'Access denied. No token provided.' }, 401);
    const subs = getStore('gollow_subscribers', []);
    let csvContent = 'Email,Active,Subscribed At\n';
    subs.forEach((item) => {
      csvContent += `${item.email},${item.active ? 'Yes' : 'No'},${item.subscribedAt}\n`;
    });
    return new Response(csvContent, {
      status: 200,
      headers: {
        'Content-Type': 'text/csv',
        'Content-Disposition': 'attachment; filename=gollow_subscribers.csv'
      }
    });
  }

  // 8. Formula Key/Values
  if (pathname === '/api/formulas') {
    if (method === 'GET') {
      if (!checkAuth()) return jsonResponse({ error: 'Access denied. No token provided.' }, 401);
      return jsonResponse(getStore('gollow_formulas', formulaConfigs));
    }
  }

  if (pathname.match(/^\/api\/formulas\/[^\/]+$/) && method === 'PUT') {
    if (!checkAuth()) return jsonResponse({ error: 'Access denied. No token provided.' }, 401);
    const id = pathname.split('/')[3];
    const configs = getStore('gollow_formulas', formulaConfigs);
    const idx = configs.findIndex(c => c.id === id);
    if (idx !== -1) {
      configs[idx].value = Number(body.value);
      if (body.description) configs[idx].description = body.description;
      setStore('gollow_formulas', configs);
      return jsonResponse(configs[idx]);
    }
    return jsonResponse({ error: 'Config parameter not found.' }, 404);
  }

  // 9. Blogs Read/Write
  if (pathname === '/api/blogs') {
    if (method === 'GET') {
      const category = searchParams.get('category');
      const search = searchParams.get('search');
      const page = Number(searchParams.get('page') || 1);
      const limit = Number(searchParams.get('limit') || 9);
      
      let blogs = getStore('gollow_blogs', initialBlogs);
      if (category && category !== 'All') {
        blogs = blogs.filter(b => b.category === category);
      }
      if (search) {
        const query = search.toLowerCase();
        blogs = blogs.filter(b => 
          b.title.toLowerCase().includes(query) || 
          b.content.toLowerCase().includes(query) ||
          (b.subtitle && b.subtitle.toLowerCase().includes(query))
        );
      }

      const total = blogs.length;
      blogs.sort((a,b) => new Date(b.publishedAt) - new Date(a.publishedAt));
      const skip = (page - 1) * limit;
      const pageItems = blogs.slice(skip, skip + limit);

      return jsonResponse({
        items: pageItems,
        pagination: {
          total,
          page,
          limit,
          totalPages: Math.ceil(total / limit)
        }
      });
    }

    if (method === 'POST') {
      if (!checkAuth()) return jsonResponse({ error: 'Access denied. No token provided.' }, 401);
      const blogs = getStore('gollow_blogs', initialBlogs);
      const slug = body.title.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
      const existing = blogs.find(b => b.slug === slug);
      const finalSlug = existing ? `${slug}-${Date.now()}` : slug;

      const newBlog = {
        id: 'blog-' + Date.now(),
        title: body.title,
        slug: finalSlug,
        subtitle: body.subtitle || '',
        content: body.content,
        imageUrl: body.imageUrl || 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&q=80&w=800',
        category: body.category,
        tags: body.tags || '',
        author: body.author,
        readTime: body.readTime || '5 min read',
        publishedAt: new Date().toISOString(),
        isPublished: true
      };
      blogs.push(newBlog);
      setStore('gollow_blogs', blogs);
      return jsonResponse(newBlog, 201);
    }
  }

  // Get single blog by slug
  if (pathname.match(/^\/api\/blogs\/[^\/]+$/)) {
    const param = pathname.split('/')[3];
    const blogs = getStore('gollow_blogs', initialBlogs);
    
    if (method === 'GET') {
      const blog = blogs.find(b => b.slug === param || b.id === param);
      if (blog) return jsonResponse(blog);
      return jsonResponse({ error: 'Blog not found.' }, 404);
    }

    if (method === 'PUT') {
      if (!checkAuth()) return jsonResponse({ error: 'Access denied. No token provided.' }, 401);
      const idx = blogs.findIndex(b => b.id === param);
      if (idx !== -1) {
        const existingBlog = blogs[idx];
        const updatedBlog = {
          ...existingBlog,
          title: body.title !== undefined ? body.title : existingBlog.title,
          subtitle: body.subtitle !== undefined ? body.subtitle : existingBlog.subtitle,
          content: body.content !== undefined ? body.content : existingBlog.content,
          imageUrl: body.imageUrl !== undefined ? body.imageUrl : existingBlog.imageUrl,
          category: body.category !== undefined ? body.category : existingBlog.category,
          tags: body.tags !== undefined ? body.tags : existingBlog.tags,
          author: body.author !== undefined ? body.author : existingBlog.author,
          readTime: body.readTime !== undefined ? body.readTime : existingBlog.readTime,
          isPublished: body.isPublished !== undefined ? body.isPublished : existingBlog.isPublished
        };
        
        if (body.title && body.title !== existingBlog.title) {
          const slug = body.title.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
          const existingSlug = blogs.find(b => b.slug === slug);
          updatedBlog.slug = existingSlug ? `${slug}-${Date.now()}` : slug;
        }

        blogs[idx] = updatedBlog;
        setStore('gollow_blogs', blogs);
        return jsonResponse(updatedBlog);
      }
      return jsonResponse({ error: 'Blog not found.' }, 404);
    }

    if (method === 'DELETE') {
      if (!checkAuth()) return jsonResponse({ error: 'Access denied. No token provided.' }, 401);
      let blogs = getStore('gollow_blogs', initialBlogs);
      blogs = blogs.filter(b => b.id !== param);
      setStore('gollow_blogs', blogs);
      return jsonResponse({ success: true, message: 'Blog post deleted successfully.' });
    }
  }

  // 10. AI Chat assistant
  if (pathname === '/api/ai/chat' && method === 'POST') {
    const messages = body.messages || [];
    const userQuery = (messages[messages.length - 1]?.content || '').toLowerCase().trim().replace(/[?.]/g, '');
    let responseText = "I can assist you with sizing arrays, calculating monthly savings, and scheduling energy audits. How can GOL LOW serve your facility?";

    if (userQuery.includes('how does solar rental work') || userQuery.includes('solar rental')) {
      responseText = "GOL LOW installs complete solar systems (panels, inverters, and battery storage) at your facility with zero upfront costs. We handle survey audits, DEWA connections, and cleanings. You pay a flat monthly lease fee that is lower than your utility savings.";
    } else if (userQuery.includes('upfront') || userQuery.includes('invest') || userQuery.includes('cost')) {
      responseText = "There is zero upfront capital investment (0 AED CAPEX). We finance and build the entire PV asset. Your monthly billing begins only after grid parallel connection is certified and power generation starts.";
    } else if (userQuery.includes('construction') || userQuery.includes('diesel')) {
      responseText = "We rent mobile solar container units integrated with modular batteries. They replace traditional noisy desert diesel generators, lowering site diesel refilling needs by up to 60%.";
    } else if (userQuery.includes('call') || userQuery.includes('contact') || userQuery.includes('callback')) {
      responseText = "Sure, please use the contact form to submit your phone number and location, or contact our central Dubai hotline at +971 4 337 7881.";
    } else if (userQuery.includes('plan') || userQuery.includes('price') || userQuery.includes('rate')) {
      responseText = "Our rental plans: Residential flat leases average 36 AED/kWp/mo; Commercial PPAs pay per kWh generated at low rates; Industrial lease-to-own starts at 20 AED/kWp/mo; and Construction containers start at 48 AED/kWp/mo.";
    }

    return jsonResponse({ content: responseText });
  }

  return originalFetch.apply(this, arguments);
};
